[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "yarn run build"
  publish = "build/"

[dev]
  command = "yarn start"
  targetPort  = 3000
  port  = 8888
  publish = "build/"
  autoLaunch  = true
  framework = "#custom"